// Code generated by protoc-gen-go.
// source: ohhai.proto
// DO NOT EDIT!

package ohhai

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type OhHai_MessageType int32

const (
	OhHai_HEARTBEAT_REQUEST  OhHai_MessageType = 0
	OhHai_HEARTBEAT_RESPONSE OhHai_MessageType = 1
	OhHai_READ_REQUEST       OhHai_MessageType = 2
	OhHai_WRITE_REQUEST      OhHai_MessageType = 3
)

var OhHai_MessageType_name = map[int32]string{
	0: "HEARTBEAT_REQUEST",
	1: "HEARTBEAT_RESPONSE",
	2: "READ_REQUEST",
	3: "WRITE_REQUEST",
}
var OhHai_MessageType_value = map[string]int32{
	"HEARTBEAT_REQUEST":  0,
	"HEARTBEAT_RESPONSE": 1,
	"READ_REQUEST":       2,
	"WRITE_REQUEST":      3,
}

func (x OhHai_MessageType) Enum() *OhHai_MessageType {
	p := new(OhHai_MessageType)
	*p = x
	return p
}
func (x OhHai_MessageType) String() string {
	return proto.EnumName(OhHai_MessageType_name, int32(x))
}
func (x OhHai_MessageType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *OhHai_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OhHai_MessageType_value, data, "OhHai_MessageType")
	if err != nil {
		return err
	}
	*x = OhHai_MessageType(value)
	return nil
}

type OhHai struct {
	MessageType       *OhHai_MessageType       `protobuf:"varint,5,req,name=message_type,enum=ohhai.OhHai_MessageType" json:"message_type,omitempty"`
	ReadRequest       *OhHai_ReadRequest       `protobuf:"bytes,1,opt,name=read_request" json:"read_request,omitempty"`
	WriteRequest      *OhHai_WriteRequest      `protobuf:"bytes,2,opt,name=write_request" json:"write_request,omitempty"`
	HeartBeatRequest  *OhHai_HeartBeatRequest  `protobuf:"bytes,3,opt,name=heart_beat_request" json:"heart_beat_request,omitempty"`
	HeartBeatResponse *OhHai_HeartBeatResponse `protobuf:"bytes,4,opt,name=heart_beat_response" json:"heart_beat_response,omitempty"`
	XXX_unrecognized  []byte                   `json:"-"`
}

func (this *OhHai) Reset()         { *this = OhHai{} }
func (this *OhHai) String() string { return proto.CompactTextString(this) }
func (*OhHai) ProtoMessage()       {}

func (this *OhHai) GetMessageType() OhHai_MessageType {
	if this != nil && this.MessageType != nil {
		return *this.MessageType
	}
	return 0
}

func (this *OhHai) GetReadRequest() *OhHai_ReadRequest {
	if this != nil {
		return this.ReadRequest
	}
	return nil
}

func (this *OhHai) GetWriteRequest() *OhHai_WriteRequest {
	if this != nil {
		return this.WriteRequest
	}
	return nil
}

func (this *OhHai) GetHeartBeatRequest() *OhHai_HeartBeatRequest {
	if this != nil {
		return this.HeartBeatRequest
	}
	return nil
}

func (this *OhHai) GetHeartBeatResponse() *OhHai_HeartBeatResponse {
	if this != nil {
		return this.HeartBeatResponse
	}
	return nil
}

type OhHai_ReadRequest struct {
	Id               *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	RangeTop         *int64 `protobuf:"varint,2,req,name=range_top" json:"range_top,omitempty"`
	RangeBottom      *int64 `protobuf:"varint,3,req,name=range_bottom" json:"range_bottom,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *OhHai_ReadRequest) Reset()         { *this = OhHai_ReadRequest{} }
func (this *OhHai_ReadRequest) String() string { return proto.CompactTextString(this) }
func (*OhHai_ReadRequest) ProtoMessage()       {}

func (this *OhHai_ReadRequest) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *OhHai_ReadRequest) GetRangeTop() int64 {
	if this != nil && this.RangeTop != nil {
		return *this.RangeTop
	}
	return 0
}

func (this *OhHai_ReadRequest) GetRangeBottom() int64 {
	if this != nil && this.RangeBottom != nil {
		return *this.RangeBottom
	}
	return 0
}

type OhHai_WriteRequest struct {
	Id               *int64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *OhHai_WriteRequest) Reset()         { *this = OhHai_WriteRequest{} }
func (this *OhHai_WriteRequest) String() string { return proto.CompactTextString(this) }
func (*OhHai_WriteRequest) ProtoMessage()       {}

func (this *OhHai_WriteRequest) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

type OhHai_HeartBeatRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *OhHai_HeartBeatRequest) Reset()         { *this = OhHai_HeartBeatRequest{} }
func (this *OhHai_HeartBeatRequest) String() string { return proto.CompactTextString(this) }
func (*OhHai_HeartBeatRequest) ProtoMessage()       {}

type OhHai_HeartBeatResponse struct {
	Id               []int64 `protobuf:"varint,1,rep,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *OhHai_HeartBeatResponse) Reset()         { *this = OhHai_HeartBeatResponse{} }
func (this *OhHai_HeartBeatResponse) String() string { return proto.CompactTextString(this) }
func (*OhHai_HeartBeatResponse) ProtoMessage()       {}

func init() {
	proto.RegisterEnum("ohhai.OhHai_MessageType", OhHai_MessageType_name, OhHai_MessageType_value)
}
