// Code generated by protoc-gen-go.
// source: filesystem.proto
// DO NOT EDIT!

package comm

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type File struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Size             *int64   `protobuf:"varint,2,req,name=size" json:"size,omitempty"`
	ModTime          *int64   `protobuf:"varint,3,req,name=mod_time" json:"mod_time,omitempty"`
	Chunks           []*Chunk `protobuf:"bytes,4,rep,name=chunks" json:"chunks,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *File) Reset()         { *this = File{} }
func (this *File) String() string { return proto.CompactTextString(this) }
func (*File) ProtoMessage()       {}

func (this *File) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *File) GetSize() int64 {
	if this != nil && this.Size != nil {
		return *this.Size
	}
	return 0
}

func (this *File) GetModTime() int64 {
	if this != nil && this.ModTime != nil {
		return *this.ModTime
	}
	return 0
}

type Chunk struct {
	Name             *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Servers          []string `protobuf:"bytes,2,rep,name=servers" json:"servers,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Chunk) Reset()         { *this = Chunk{} }
func (this *Chunk) String() string { return proto.CompactTextString(this) }
func (*Chunk) ProtoMessage()       {}

func (this *Chunk) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

type Directory struct {
	Name             *string      `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	SubDirs          []*Directory `protobuf:"bytes,2,rep,name=sub_dirs" json:"sub_dirs,omitempty"`
	Files            []*File      `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *Directory) Reset()         { *this = Directory{} }
func (this *Directory) String() string { return proto.CompactTextString(this) }
func (*Directory) ProtoMessage()       {}

func (this *Directory) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func init() {
}
